[package]
name = "taven"
version = "0.1.0"
edition = "2024"

[dependencies]
taven_internal ={ path = "crates/taven_internal", version = "0.1.0"}

[dev-dependencies]

[workspace]
members = [
    "crates/taven_core", 
    "crates/taven_internal",
]
